# Chance (in percent) for the ritual to succeed
success-chance: 100.0

# The block that must be right-clicked to start the ritual
center-block: JACK_O_LANTERN

# The block that must surround the center (8 total)
surround-block: CARVED_PUMPKIN
